
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WilcoCon.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public Employee()
    {

        this.TimeCards = new HashSet<TimeCard>();

    }


    public int EmployeeId { get; set; }

    public string SSN { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public int ZipCode { get; set; }

    public string TelephoneNumber { get; set; }

    public string DOB { get; set; }

    public string Gender { get; set; }

    public string MaritalStatus { get; set; }

    public int NumberOfDeductions { get; set; }

    public int EEOCOde { get; set; }



    public virtual ICollection<TimeCard> TimeCards { get; set; }

}

}
