
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WilcoCon.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PayScale
{

    public int PayScaleId { get; set; }

    public decimal BasicHourlyRate { get; set; }

    public decimal FringeBenefitPayments { get; set; }

    public int SkillId { get; set; }

    public int ProjectId { get; set; }



    public virtual JobClassification JobClassification { get; set; }

    public virtual Project Project { get; set; }

}

}
